txt = "AMO FAZER EXERCICIO NO URI"

# print(f"<{txt}>")
print("<%s>"%(txt))
# print(f"<{txt:>30}>")
print("<%30s>"%(txt))
# print(f"<{txt[:20]}>")
print("<%.20s>"%(txt))
# print(f"<{txt}>")
print("<%-20s>"%(txt))
# print(f"<{txt:30}>")
print("<%-30s>"%(txt))
# print(f"<{txt}>")
print("<%.30s>"%(txt))
# print(f"<{txt[:20]:>30}>")
print("<%30.20s>"%(txt))
# print(f"<{txt[:20]:<30}>")
print("<%-30.20s>"%(txt))
